# Generated by Django 2.2.16 on 2020-11-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='status',
            new_name='available',
        ),
    ]
