# Generated by Django 2.2.16 on 2020-11-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20201109_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='id_vehicle_in_auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Vehicle_in_auction'),
        ),
    ]
