# Generated by Django 2.2.16 on 2020-11-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_offers_id_vehicle_in_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='id_vehicle_in_auction',
            new_name='vehicle_in_auction',
        ),
    ]
