# Generated by Django 2.2.16 on 2020-11-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20201111_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sold', models.FloatField()),
                ('date', models.DateField(null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Offers')),
            ],
        ),
    ]
